training:
  num_episodes: 20000
  max_steps_per_episode: 5
  log_interval: 10
  save_interval: 500
  speed: 10000000

env:
  map_size: 4
  is_slippery: False

agent:
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  learning_rate: 0.0005
  target_update_freq: 10 # in episodes
  hidden_size: 128

memory:
  buffer_size: 10000
  batch_size: 64