training:
  log_interval: 100
  max_steps_per_episode: 200
  num_episodes: 1000
  save_interval: 500
  speed: 10000000

testing:
  num_episodes: 1000
  speed: 10000000

reward:
  goal: 1.0
  hole: 0
  wall: -0.1
  ice: 0

agent:
  model_type: CNN

  epsilon_decay: 2000
  epsilon_end: 0.01
  epsilon_start: 1.0

  gamma: 0.99
  learning_rate: 0.0005
  target_update_freq: 10

  mlp:
    hidden_size: 128

  cnn:
    hidden_size: 128
    input_shape: [4, 4, 4] #[channels, height, width]
    conv_channels: 16

env:
  is_slippery: false
  map_size: 4
  goal: 0.7
  hole: 0
  ice: 0
  agent: 1

memory:
  batch_size: 64
  buffer_size: 10000